# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Election Updates
description: >- # this means to ignore newlines until "baseurl:"
  This is a basic site to share election updates via social channels.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://common-cause-share.netlify.app" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics_ua: UA-????????-??
fb_app_id: 3112531338794556

# Build settings
theme: uswds-jekyll
font-awesome:
  assets: true

styles:
  - https://use.fontawesome.com/releases/v5.0.7/css/all.css

scripts:
  - https://identity-js.netlify.com/v1/netlify-identity-widget.js