backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "assets/uploads" # Folder where user uploaded files should go

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "post"
    label: "Post"
    folder: "_posts"
    extension: "md"
    sort: "date:desc"
    create: true
    preview: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}-{{lang}}"
    path: "{{year}}/{{month}}/{{day}}/{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Language", name: "lang", widget: "select", options: ["en", "es"], default: "en"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Share Header", name: "share_header", widget: "string", default: "You're almost done!"}
      - {label: "Share Subhead", name: "share_subhead", widget: "string", default: "Use these sharing tools to spread the word"}
      - {label: "Share Text", name: "share_text", widget: "string"}
      - {label: "Share Image", name: "share_image", widget: "image"}
