backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "assets/uploads" # Folder where user uploaded files should go
site_url: "https://share.commoncause.org"
show_preview_links: true

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "post"
    label: "Post"
    folder: "_posts"
    extension: "md"
    sort: "date:desc"
    create: true
    editor:
      preview: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "/{{shortlink}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Language", name: "lang", widget: "select", options: ["en", "es"], default: "en"}
      - {label: "Translation Reference", name: "lang_ref", widget: "string", required: false, hint: "Key to link translations together"}
      - {label: "Permalink", name: "permalink", widget: "string", hint: "Long link for page. Suggest '/YYYY/MM/DD/title/'"}
      - {label: "Shortlink", name: "shortlink", widget: "string", hint: "Short link to send via text. Do not include leading slash!"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1", hint: "Page heading and title"}
      - {label: "Body", name: "body", widget: "markdown", hint: "Page body"}
      - {label: "Share Header", name: "share_header", widget: "string",
          default: "You're almost done!", hint: "Sidebar heading"}
      - {label: "Share Subhead", name: "share_subhead", widget: "string",
          default: "Use these sharing tools to spread the word", hint: "Sidebar secondary"}
      - {label: "Share Text", name: "share_text", widget: "string"}
      - {label: "Share Image", name: "share_image", widget: "image", required: false}
      - {label: "Share Video", name: "share_video", hint: "Show video instead of image", required: false, widget: youtube, extraInfo: true, APIkey: "AIzaSyCWbPgh6Py5rl4Zzmu2AFGDCzjnrGMZRMs"}
      - {label: "Share Hashtags", name: "share_hashtags", widget: "string", required: false}
  - name: "page"
    label: "Pages"
    files:
        - name: "index"
          label: "Index page"
          file: "/index.md"
          fields:
            - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
            - {label: "Title", name: "title", widget: "string"}
            - label: Hero
              name: hero
              widget: object
              fields:
                - {label: "Background Image", name: "image", widget: "image"}
                - label: "Callout"
                  name: "callout"
                  widget: "object"
                  fields:
                    - {label: "Line 1", name: "alt", widget: "string"}
                    - {label: "Line 2", name: "text", widget: "string"}
                - label: "Content"
                  name: "content"
                  widget: "string"
                - label: "Button"
                  name: "button"
                  widget: "object"
                  fields:
                    - {label: "Link", name: "href", widget: "string"}
                    - {label: "Text", name: "text", widget: "string"}
            - label: Tagline
              name: tagline
              widget: string
            - label: Intro
              name: Intro
              widget: string
            - label: Graphics
              name: graphics
              widget: list
              fields: 
                - label: Image
                  name: image
                  widget: "object"
                  fields: 
                    - {label: "source", name: src, widget: "image", default: "/assets/uswds/img/circle-124.png"}
                    - {label: "alt", name: alt, widget: "string"}
                - label: Title
                  name: title
                  widget: string
                - label: Link
                  name: href
                  widget: string
                - label: Description
                  name: description
                  widget: string
