backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections:
  - name: "post"
    label: "Post"
    folder: "_posts"
    sort: "date:desc"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Share Header", name: "share_header", widget: "string", default: "You're almost done!"}
      - {label: "Share Subhead", name: "share_subhead", widget: "string", default: "Use these sharing tools to spread the word"}
      - {label: "Share Text", name: "share_text", widget: "string"}
      - {label: "Share Image", name: "share_image", widget: "image"}
